repos:
- repo: https://github.com/pypeaday/ansible-vault-pre-commit
  rev: main
  hooks:
  - id: encryption-check
    name: Ansible Vault Encryption Check
    description: Checks that vault files are encrypted
    entry: encryption-check.sh
    files: (private)
    language: script
