#!/usr/bin/env bash
pushd $HOME/dotfiles

for package in $(cat dotfiles.txt)
do
	stow -D $package || true
	stow $package
done

if [[ $USER == *"3"* ]]; then
	stow -D iron
	stow iron
elif [[ $USER == *"81"* ]]; then
	stow -D fin
	stow fin
else
	# pass since I'm at home
	echo "Skipping..."
fi

echo "Getting k9s skins..."
OUT="${K9S_CONFIG_DIR:-$HOME/.config}/k9s/skins"
mkdir -p "$OUT"
curl -L https://github.com/catppuccin/k9s/archive/main.tar.gz | tar xz -C "$OUT" --strip-components=2 k9s-main/dist
popd
