#!/usr/bin/env bash
#
pushd $DOTFILES
if [[ $USER == "paynen3" ]]
then
    echo "Stowing stuff for work"
    stow -D work
    stow work

    eval $HOME/dotfiles/scripts/.local/bin/triple-monitor
    eval $HOME/dotfiles/polybar/launch.sh
    eval $HOME/dotfiles/picom/.config/picom/launch_picom
else
    echo "Stowing stuff for home"
    stow -D personal
    stow personal
fi

for folder in $(echo $STOW_FOLDERS | sed "s/,/ /g")
do
    stow -D $folder
    stow $folder
done

popd
