[tank/encrypted/nas]
    use_template = production
    recursive = no
[tank/encrypted/nas/documents]
    use_template = production
[tank/encrypted/nas/dump]
    use_template = production
[tank/nas/media]
    recursive = no
    use_template = media
[tank/encrypted/docker]
    use_template = production
    recursive = no
[tank/vms]
    use_template = production
    recursive = yes
    process_children_only = yes

#############################
# templates below this line #
#############################
[template_media]
        frequently = 1
        hourly = 1
        daily = 7 
        monthly = 0
        yearly = 0
        autosnap = yes
        autoprune = yes

[template_production]
        frequently = 4
        hourly = 36
        daily = 7
        monthly = 1
        yearly = 0
        autosnap = yes
        autoprune = yes
