#!/bin/bash

# hcio start
curl https://hc-ping.com/uWDfVXr2W4O9rF7deuOEog/syncoid/start

echo "Syncing nic@ghost:tank/encrypted!" >> /home/nic/mycron.log
syncoid --no-sync-snap --sendoptions=w --no-privilege-elevation nic@ghost:tank/encrypted tank/encrypted

echo "Syncing nic@ghost:tank/encrypted/10Fold!" >> /home/nic/mycron.log
syncoid --no-sync-snap --sendoptions=w --no-privilege-elevation nic@ghost:tank/encrypted/10Fold tank/encrypted/10Fold

echo "Syncing nic@ghost:tank/encrypted/nas! excluding tank/encrypted/nas/media" >> /home/nic/mycron.log
syncoid --no-sync-snap --sendoptions=w -r --exclude tank/encrypted/nas/media --no-privilege-elevation nic@ghost:tank/encrypted/nas tank/encrypted/nas

echo "Syncing nic@ghost:tank/encrypted/fs!" >> /home/nic/mycron.log
syncoid --no-sync-snap --sendoptions=w -r --no-privilege-elevation nic@ghost:tank/encrypted/fs tank/encrypted/fs

echo "Syncing nic@ghost:tank/encrypted/vms!" >> /home/nic/mycron.log
# syncoid --skip-parent --no-sync-snap --sendoptions=w -r --no-privilege-elevation nic@ghost:tank/encrypted/vms tank/encrypted/vms
syncoid --no-sync-snap --sendoptions=w --no-privilege-elevation nic@ghost:tank/encrypted/vms tank/encrypted/vms
syncoid --no-sync-snap --sendoptions=w --no-privilege-elevation nic@ghost:tank/encrypted/vms/pihole tank/encrypted/vms/pihole
syncoid --no-sync-snap --sendoptions=w --no-privilege-elevation nic@ghost:tank/encrypted/vms/homeassistant tank/encrypted/vms/homeassistant
syncoid --no-sync-snap --sendoptions=w --no-privilege-elevation nic@ghost:tank/encrypted/vms/win10 tank/encrypted/vms/win10
syncoid --no-sync-snap --sendoptions=w --no-privilege-elevation nic@ghost:tank/encrypted/vms/block-subnet-router tank/encrypted/vms/block-subnet-router

echo "Syncing nic@ghost:tank/encrypted/docker!" >> /home/nic/mycron.log
syncoid --no-sync-snap --sendoptions=w --no-privilege-elevation nic@ghost:tank/encrypted/docker tank/encrypted/docker

# hcio
curl -m 10 --retry 5 https://hc-ping.com/uWDfVXr2W4O9rF7deuOEog/syncoid
