#!/bin/bash

echo `date` >> /home/nic/mycron.log

# Pulling zfs datasets that don't need re-created. Only nas needs rebuilt from
# files then eventually the zpool on venus will be the main pool

# echo "rsyncing relevant media folders" >> /home/nic/mycron.log
# ./migrate-media.sh

# echo "rsyncing relevant NAS folders" >> /home/nic/mycron.log
# ./migrate-nas.sh

echo "Syncing nic@hogwarts:tank/nas!" >> /home/nic/mycron.log
syncoid --no-sync-snap --sendoptions=w -r --no-privilege-elevation nic@hogwarts:tank/encrypted/nas tank/encrypted/nas

echo "Syncing nic@hogwarts:tank/vms!" >> /home/nic/mycron.log
syncoid --skip-parent --no-sync-snap --sendoptions=w -r --no-privilege-elevation nic@hogwarts:tank/encrypted/vms tank/encrypted/vms

echo "Syncing nic@hogwarts:tank/10Fold!" >> /home/nic/mycron.log
syncoid --no-sync-snap --sendoptions=w -r --no-privilege-elevation nic@hogwarts:tank/encrypted/10Fold tank/encrypted/10Fold

echo "Syncing nic@hogwarts:tank/docker!" >> /home/nic/mycron.log
syncoid --no-sync-snap --sendoptions=w --no-privilege-elevation nic@hogwarts:tank/encrypted/docker tank/encrypted/docker
