#! /bin/bash
killall -q picom
# Wait until the processes have been shut down
while pgrep -x picom >/dev/null; do sleep 1; done
picom -f --experimental-backend -b --config ~/.config/picom/picom.conf &

