[global]
require-virtualenv = True
#extra-index-url = https://avant.jfrog.io/artifactory/api/pypi/main-pypi
extra-index-url = https://pypi.services.global.avant.com/simple
trusted-host = pypi.services.global.avant.com
timeout = 10
